apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    app: multi-container
    type: allapp
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - name: redis
          containerPort: 6379
      resources:
        requests:
          memory: "250Mi"
        limits:
          memory: "250Mi"
    - name: memcached
      image: memcached
      ports:
        - name: memcached
          containerPort: 11211
      resources:
        requests:
          memory: "250Mi"
        limits:
          memory: "250Mi"
    - name: nginx
      image: nginx
      ports:
        - name: nginx
          containerPort: 80
      resources:
        requests:
          memory: "250Mi"
        limits:
          memory: "250Mi"
    - name: mysql
      image: mysql
      ports:
        - name: mysql
          containerPort: 3306
      resources:
        requests:
          memory: "250Mi"
        limits:
          memory: "250Mi"