apiVersion: v1
kind: Service
metadata:
  name: redis-service

spec:
  type: NodePort
  ports:
    - name: redis-service
      port: 6379
      targetPort: 6379
      nodePort: 30010

  selector:
    app: web-cache
    type: caching